// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ValuationDiamond.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public bool PayStatus { get; set; }

    public string Status { get; set; }

    public string Payment { get; set; }

    public DateTime Day { get; set; }

    public int Quantity { get; set; }

    public double TotalAmount { get; set; }

    public int CustomerId { get; set; }

    public string OrderCode { get; set; }

    public string StaffName { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}