// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ValuationDiamond.Data.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int ServiceId { get; set; }

    public string Status { get; set; }

    public double? Price { get; set; }

    public int OrderId { get; set; }

    public string DetailCode { get; set; }

    public string Description { get; set; }

    public double? EstimateLength { get; set; }

    public virtual Order Order { get; set; }

    public virtual Service Service { get; set; }

    public virtual ICollection<ValuateDiamond> ValuateDiamonds { get; set; } = new List<ValuateDiamond>();
}