// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ValuationDiamond.Data.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public string Name { get; set; }

    public float? Price { get; set; }

    public string Decription { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}