// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ValuationDiamond.Data.Models;

public partial class Staff
{
    public int StaffId { get; set; }

    public string Name { get; set; }

    public string Role { get; set; }

    public bool Status { get; set; }
}