// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ValuationDiamond.Data.Models;

public partial class ValuateDiamond
{
    public int ValuateDiamondId { get; set; }

    public double Price { get; set; }

    public TimeSpan Time { get; set; }

    public string ValuationStaffName { get; set; }

    public int OrderDetailId { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual ICollection<ValuationCertificate> ValuationCertificates { get; set; } = new List<ValuationCertificate>();
}